name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for your feedback. I'll review this as soon as possible.

            If this is a bug report, please include relevant logs to help us debug the problem.
          pr-message: |
            Hello! Thank you for your interest in contributing! I'll review the proposed changes as soon as possible.

            If you are fixing a bug, please reference the issue number in the description.

            If you are implementing a feature request, please check first if the feature will be accepted.
